opt_in_rules:
- trailing_newline

disabled_rules:
- trailing_whitespace
- type_name
- force_cast
- type_body_length
- file_length
- variable_name
- cyclomatic_complexity
- valid_docs
- missing_docs
- opening_brace
- line_length
- force_try

force_try: warning

line_length: 150

excluded: # Lint対象から外すファイルのあるパスを記述
- Pods
- Carthage

# 関数の長さ
function_body_length:
- 100 # warning
- 300 # error

# 引数の数
function_parameter_count:
- 5 #warning
- 10 #error
