language: objective-c
osx_image: xcode8
xcode_project: Tsumiki.xcodeproj
xcode_scheme: Tsumiki
env:
  global:
  - DESTINATION="platform=iOS Simulator,name=iPhone 7"
  - FRAMEWORK_NAME=Tsumiki
branches:
  only:
  - master
  - "/bugfix.*/"
  - "/^develop.*/"
  - "/^v?[0-9\\.]+/"
script:
- set -o pipefail
- xcodebuild test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -sdk iphonesimulator -destination "$DESTINATION" | xcpretty -c
before_deploy:
- carthage build --no-skip-current
- carthage archive "$FRAMEWORK_NAME"
deploy:
  provider: releases
  api_key:
    secure: hfonYOwYqwtUDRrfVQ2WtpWauL3kZZzGUqoPXl3ICf3lwwkUaw2Uyqc7S53GWfnPamLpmY0mPDmzVmrlOqBiYDrN22Z84VjlagbmPUjKucGRTZRvHA8Veqe2Iqi/ceG0uRYUQqWN5eLOKgb9QRFqZWCawKD4kCFWNT2IZNBeWUoWTG9BWepqNFD763/BP6uiqCkbh7Tdr2P3h75uG5jPlBgqIpvif04NpMbu51/Ny8mYhgha33SfduhVzAaPp0vJJC4CAyK0zllBWN1oRHU1UO6I/FoFRFjlExUH3kbPs+0WSF64fkQ6vnaKvARiC5cQq9uvQTQz0M9/44dJRqS/E2q91W79MAGNFhGTyIQaq+la0drDC0Dpvb4PQFcoAvlClFKpyVDnxT/Rd3wMn/E3yUBhb/GMRZcHTzOYAYhsKcWvGogT+YQ52YkZ9VNxRZITBrp4jKgeEv4DBSwbOKgDYY245d7tck8crOPkG0gV0oIZR9rRCw3aTDnMvjev6GnItEqsYKlh51qm0kfJj//FPpLAbsjPQdZLOtu+KzP29LPcGNYv9iaik4qYZKvJ5xeIUZOSU8WXKHURxbEgLODA+Dx2rDS9V++dIW12eP8ryOJr4efcx4zX/Wr2emVuWqhKuC0Wqx1GeastYJokDacg5UEBgpUnSdAY3GBHLCE+rSg=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: "$TRAVIS_REPO_SLUG"
    tags: true
notifications:
  email: false
  slack:
    secure: Z4S7jnJk1nesu1FK13218coFrEqBSI+P5ruDA9FNgU72A06fh/kRCLrBPJhjQGzQXR4n8kCONXC3SJULYWRivF8M/E2hox88j0+Ii5mzPIfUWD6WejXtJQ/yu9djq3TbXNoK0rCsAU4rkLnfYSYifgYayudW/ZjFjOWPmQ+SqYG5bTmTk501EU6uD6OcDrWpKUbA9neG2RJI3LRyiDNxwm+3XeNZJRlD/vhD1xnx4obv8T2yF+zr3rSL33LqP0aR2djjTGQhg67mWUiZTcbW6n+zJDI+BCB6ZsTs3itJObbgkvuOa1e25V4DXjcj5A5t4R564IJ/OjBePaC/GRo46Gm3enLEN71OXhEKjkQDZzorWOiEMo3GAJmQZmKsukSDu8iG6kfC07+4bVS3Qf4M7lIOJbRC2SwvycCfVJDT/uexG2yX5+bVYKBHBIx6w2dRDscoRsiQ6wbO2ZbSjzfUbVKmWDYSkopRQaA/rZ/GwAJDVMWINeGqhvnN6CPRBHa8rtd6XAmAhX+GQA1UCh6Cx6Bn2FyVdj+2kH/AoIjjMTv8itzCU9cPvLIBNMcQywjZkZoIbrHjmSa+I+KELSNRgkVUxgBNO2NnfiuxApjOjNN+iNmlZszsO74X+0Rq0/xiJizuISEz6LEEaozcV9DDsjNPc5WqkrZGhuqFLYpT86Y=
